#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index


#show:
#  path: /biens/show
#  controller: App\Controller\PropertyController::show